# Generated by Django 5.0.7 on 2024-07-22 11:54

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('topics', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Conference', 'Conference'), ('Seminar', 'Seminar'), ('Corporate event', 'Corporate event'), ('Panel discussion', 'Panel discussion'), ('Other', 'Other')], default='none', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=event.models.get_image_upload_path)),
            ],
        ),
    ]
