# Generated by Django 5.0.7 on 2024-07-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
        ('speaker', '0003_rename_location_speaker_city_speaker_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='applied_by',
            field=models.ManyToManyField(blank=True, null=True, to='speaker.speaker'),
        ),
    ]
