# Generated by Django 5.0.7 on 2024-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_speakers'),
        ('speaker', '0003_rename_location_speaker_city_speaker_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(related_name='events', to='speaker.speaker'),
        ),
    ]
