# Generated by Django 5.0.7 on 2024-07-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_state'),
        ('event', '0005_remove_event_speakers'),
    ]

    operations = [
    ]
