services:
  backend:
    image: ghcr.io/magicmiren/panelista:latest
    ports:
      - '8000:8000'
    command: 'sh /scripts/dev.sh'
    volumes:
      - ./backend:/backend
      - ./scripts:/scripts

    env_file:
      - ./envs/dev.env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: