# Generated by Django 5.0.7 on 2024-07-22 11:54

import speaker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.TextField(blank=True)),
                ('current_job_title', models.CharField(blank=True, max_length=255)),
                ('career_description', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to=speaker.models.get_profile_picture_upload_path)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('willingness_to_travel', models.CharField(blank=True, choices=[('0km', '0km'), ('50km', '50km'), ('100km', '100km'), ('100+km', '100+km')], max_length=10)),
                ('pronouns', models.CharField(blank=True, choices=[('She/her', 'She/her'), ('He/him', 'He/him'), ('They/them', 'They/them'), ('Other', 'Other')], max_length=50)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('professional_experience', models.CharField(blank=True, choices=[('None', 'None'), ('1-3y', '1-3 years'), ('3-5y', '3-5 years'), ('5-10y', '5-10 years'), ('10-15y', '10-15 years'), ('15-20y', '15-20 years'), ('20-25y', '20-25 years'), ('25+ y', 'More than 25 years')], max_length=50)),
                ('cultural_background', models.TextField(blank=True)),
                ('speaker_experience', models.CharField(blank=True, choices=[('None', 'None'), ('1-5', '1-5 engagements'), ('5-10', '5-10 engagements'), ('10-20', '10-20 engagements'), ('20+', 'More than 20 engagements'), ('Full-time', 'Full-time / professional speaker')], max_length=50)),
                ('languages', models.TextField(blank=True)),
                ('engagement_types', models.TextField(blank=True)),
                ('max_event_size', models.CharField(blank=True, choices=[('<25', 'Less than 25 attendees'), ('25-100', '25-100 attendees'), ('100-500', '100-500 attendees'), ('500-1000', '500-1000 attendees'), ('1000+', 'More than 1000 attendees')], max_length=50)),
                ('general_availability', models.TextField(blank=True)),
                ('contact_preferences', models.TextField(blank=True)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('confirmation', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
