# Generated by Django 5.0.7 on 2024-07-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='speaker',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='speaker',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
