# Generated by Django 5.0.7 on 2024-07-22 11:54

import organizer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, upload_to=organizer.models.get_profile_picture_upload_path)),
                ('experience', models.CharField(blank=True, choices=[('None', 'None'), ('1-3y', '1-3 years'), ('3-5y', '3-5 years'), ('5-10y', '5-10 years'), ('10-15y', '10-15 years'), ('15-20y', '15-20 years'), ('20-25y', '20-25 years'), ('25+ y', 'More than 25 years')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
