# Generated by Django 5.0.7 on 2024-07-22 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='speaker.speaker'),
        ),
    ]
