# Generated by Django 5.0.7 on 2024-07-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='event',
        ),
    ]
