name: CI/CD Pipeline

# Trigger the workflow on push to the main or master branch, or manually
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v4

    # Step 2: Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}

    # Step 4: Build and push Docker images to GitHub Container Registry
    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/magicmiren/panelista:latest .
        docker build -t ghcr.io/magicmiren/panelista:master .
        docker push ghcr.io/magicmiren/panelista:latest
        docker push ghcr.io/magicmiren/panelista:master

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Deploy to DigitalOcean Droplet using SSH
    - name: Deploy to DigitalOcean Droplet
      uses: docker/login-action@v1
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ../../
          docker-compose down
          docker-compose pull
          docker-compose up -d
